### ISSUE TITLE
Random MigrationNotFound errors while migrating after adding new migrations

### ISSUE THREAD

**Issue by christianbradley** [bocodigitalmedia/boco-migrate#5]
Using RedisAdapter

```
/bin/boco-migrate migrate 002                                                                                                             ✱ ◼
Potentially unhandled rejection [1] MigrationNotFound: Migration not found
    at Migrator.findMigrationIndexById (/Users/christianbradley/src/boco-delphi-v2/node_modules/boco-migrate/build/index.js:300:15)
    at Migrator.migrate (/Users/christianbradley/src/boco-delphi-v2/node_modules/boco-migrate/build/index.js:347:30)
    at CLI.migrate (/Users/christianbradley/src/boco-delphi-v2/node_modules/boco-migrate/build/index.js:472:23)
    at /Users/christianbradley/src/boco-delphi-v2/node_modules/boco-migrate/build/index.js:573:28
    at tryCatchReject (/Users/christianbradley/src/boco-delphi-v2/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/Users/christianbradley/src/boco-delphi-v2/node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (/Users/christianbradley/src/boco-delphi-v2/node_modules/when/lib/makePromise.js:592:4)
    at Pending.run (/Users/christianbradley/src/boco-delphi-v2/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/Users/christianbradley/src/boco-delphi-v2/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/Users/christianbradley/src/boco-delphi-v2/node_modules/when/lib/Scheduler.js:27:9)
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)
```

**Comment by christianbradley** [comment]
Looks like somehow numerical-ish strings, (ie: "002") are getting converted to numbers...

**Comment by christianbradley** [comment]
This is due to the CLI parsing arguments as numbers. We should make sure that it parses them as strings instead
